#!/bin/bash
# demo

# This is a simple demonstration script for sat_solve and sat_verify
# See README.txt for more details

INSTALL_DIR=$(dirname "$0")/..

$INSTALL_DIR/bin/sat_solve $INSTALL_DIR/example/cnf_1 > $INSTALL_DIR/work/solution

cat $INSTALL_DIR/work/solution

$INSTALL_DIR/bin/sat_verify $INSTALL_DIR/example/cnf_1 < $INSTALL_DIR/work/solution

